/* Everyday job and creativity replacements.
 *
 * These replace thirty abstract challenges without increasing the size of the
 * challenge bank. Every fact or workplace rule needed to answer is included in
 * the scenario. Creative challenges score how well an idea fits clear limits;
 * the player's own idea remains optional and is never graded.
 */
const MTC_EVERYDAY_REPLACEMENTS = [
  {
    id: "gym-flaw-1", title: "A Customer Shouts About Their Coffee", emoji: "☕", difficulty: 1,
    areas: ["work", "relationships"], frameworks: ["communication", "emotional-regulation", "decision-making"],
    scenario: "You work in a coffee shop. A customer says their drink is wrong and raises their voice. The shop rule says to stay calm, check the order and involve the manager if anyone becomes threatening.",
    problem: "Solve the complaint without matching the customer's anger.",
    steps: [
      ["What should you do first?", "Listen, check the order and speak calmly", "This finds the real problem without adding more anger.", ["Tell them to calm down", "Raise your voice so they listen", "Ignore them and serve the next person"]],
      ["The drink was made incorrectly. What is the clearest response?", "Acknowledge the mistake and offer the shop's normal replacement", "A clear apology and practical fix deal with the real complaint.", ["Explain why the customer caused the mistake", "Offer something the shop cannot provide", "Argue about how busy the shop is"]],
      ["The customer threatens a member of staff. What now?", "Step back and involve the manager or security under the shop rule", "Safety comes before finishing the complaint yourself.", ["Threaten them back", "Block the exit", "Keep arguing until they apologise"]],
    ],
    principle: "Deal with the problem, not the volume. Listen, state the facts and use the safety rule when behaviour becomes threatening.",
    limit: "A calm response does not mean accepting abuse. Set a boundary and get help when the behaviour crosses it.",
  },
  {
    id: "gym-flaw-2", title: "The Factory Machine Sounds Wrong", emoji: "🏭", difficulty: 1,
    areas: ["work", "safety"], frameworks: ["situational-awareness", "risk-assessment", "decision-making"],
    scenario: "You work near a packing machine. It starts making a new grinding sound. The posted rule says: do not reach inside, press the normal stop button if safe, keep people back and tell the trained supervisor.",
    problem: "Follow the stated safety rule instead of guessing at the fault.",
    steps: [
      ["What is the important new clue?", "The machine is making a sound it did not make before", "A change can warn of a developing fault even when the machine still runs.", ["The shift is nearly over", "The boxes look normal", "Nobody else has complained"]],
      ["What should you do if the stop button is safe to reach?", "Use it, keep people back and report the problem", "This follows every part of the rule without touching the machine.", ["Reach inside to feel what is loose", "Keep it running until the break", "Hit the machine to stop the noise"]],
      ["Why should a trained person check it?", "The cause is unknown and opening it needs the right training", "Reporting uncertainty is safer than attempting a repair you are not trained to make.", ["Supervisors are always right", "The sound proves the motor is broken", "Only managers may hear unusual sounds"]],
    ],
    principle: "Notice changes, stop safely and pass technical faults to someone trained to deal with them.",
    limit: "Not every new sound means serious danger. The stated procedure lets the right person check without gambling with safety.",
  },
  {
    id: "gym-flaw-3", title: "A Student Is Falling Behind", emoji: "📚", difficulty: 1,
    areas: ["work", "study"], frameworks: ["communication", "questioning", "decision-making"],
    scenario: "You teach a class. One student has stopped handing in work and avoids questions. You do not know why. School guidance says to speak privately, ask open questions and report any safeguarding concern.",
    problem: "Find out what support is needed without making a public assumption.",
    steps: [
      ["What should you avoid assuming?", "That the student is lazy", "Missing work can have many causes, and the facts given do not show which one applies.", ["That work is missing", "That a private talk is possible", "That the guidance exists"]],
      ["What is a useful private question?", "I noticed some work is missing. Is anything making it hard to complete?", "It names the fact and gives the student room to explain.", ["Why are you so lazy?", "Everyone else can do it, so why can't you?", "Will you promise never to miss work again?"]],
      ["The student mentions feeling unsafe at home. What now?", "Follow the school's safeguarding procedure", "A possible safety concern must go to the people trained and responsible for acting.", ["Promise to keep it completely secret", "Investigate the family yourself", "Discuss it with the whole class"]],
    ],
    principle: "Start with what you observed, ask without blame and use the proper support route when safety may be involved.",
    limit: "Open questions do not remove the teacher's duty to act. A safeguarding concern must still be reported through the stated procedure.",
  },
  {
    id: "gym-flaw-4", title: "A Child Steps Near the Road", emoji: "🚗", difficulty: 1,
    areas: ["safety"], frameworks: ["hazard-perception", "risk-assessment", "decision-making"],
    scenario: "You are driving at 20 mph past parked cars. A ball rolls into the road and you can see a child's shoes between two cars. The road behind you is clear.",
    problem: "Recognise the developing hazard before the child enters the road.",
    steps: [
      ["What does the ball suggest?", "A child may follow it into the road", "The ball and the visible shoes together create a clear developing hazard.", ["The road is now closed", "The parked cars will move", "The speed limit has changed"]],
      ["What is the safest immediate response?", "Slow down and be ready to stop", "Reducing speed creates more time and stopping distance if the child appears.", ["Speed up before the child arrives", "Sound the horn and keep the same speed", "Move onto the pavement"]],
      ["Why is waiting for the child to appear weaker?", "It leaves less time and distance to stop", "Hazard awareness means acting on a strong warning, not waiting for the danger to be fully visible.", ["Children may never cross roads", "Brakes only work below 20 mph", "Parked cars always have priority"]],
    ],
    principle: "Look for clues that a hazard is developing and create time to respond before it becomes an emergency.",
    limit: "A ball does not prove a child will run out. Slowing down is still a small, safe response to a serious possibility.",
  },
  {
    id: "gym-flaw-5", title: "The Emergency Alarm at a Nuclear Site", emoji: "🚨", difficulty: 1,
    areas: ["work", "safety"], frameworks: ["instruction-following", "prioritisation", "risk-assessment"],
    scenario: "You are a visitor at a nuclear site. Your badge lists the alarm rule: stop work, leave by the marked route, go to the meeting point and report to the person in charge. Do not collect belongings or return until told.",
    problem: "Put safety instructions ahead of curiosity or personal items.",
    steps: [
      ["The alarm sounds. What should you do first?", "Stop work and use the marked route", "That is the first action on the rule provided in the scenario.", ["Search online for the cause", "Collect your coat and bag", "Wait to see what everyone else does"]],
      ["Where should you go?", "The stated meeting point", "The meeting point lets staff account for people and give further instructions.", ["Your car", "The nearest office", "Back to the entrance desk"]],
      ["You remember your phone inside. What now?", "Stay at the meeting point and tell the person in charge", "The rule clearly says not to return for belongings.", ["Go back quickly on your own", "Ask another visitor to get it", "Leave the site without reporting"]],
    ],
    principle: "In a high-risk setting, follow the clear emergency procedure in order and let trained staff manage the unknown details.",
    limit: "Procedures differ by site. This challenge tests the instructions shown here, not specialist nuclear knowledge.",
  },
  {
    id: "gym-flaw-6", title: "A Child Has a Public Meltdown", emoji: "🧸", difficulty: 1,
    areas: ["relationships", "home"], frameworks: ["emotional-regulation", "communication", "decision-making"],
    scenario: "Your five-year-old becomes overwhelmed in a busy shop and starts shouting. They are safe, but noise and people are making things worse. You need to leave soon.",
    problem: "Lower the pressure first, then deal with the behaviour.",
    steps: [
      ["What should come first?", "Move to a quieter safe place and speak calmly", "Reducing noise and attention can help the child regain control.", ["Give a long lecture in front of everyone", "Shout louder than the child", "Threaten a punishment you will not use"]],
      ["What is a clear short message?", "You are safe. We are going somewhere quieter now", "It gives reassurance and one simple next step.", ["You always ruin everything", "Stop immediately or I will leave you here", "Explain yourself properly right now"]],
      ["When should you discuss what happened?", "After both of you are calmer", "Learning and problem-solving work better when the immediate overload has passed.", ["Only while the child is shouting", "Never mention it again", "In front of strangers so they agree"]],
    ],
    principle: "Regulate first, connect second and teach later. A calm boundary is easier to follow than a public argument.",
    limit: "Calm support is not the same as removing every boundary. The behaviour can still be discussed once everyone is able to listen.",
  },
  {
    id: "gym-flaw-7", title: "A Warehouse Label Does Not Match", emoji: "📦", difficulty: 1,
    areas: ["work", "safety"], frameworks: ["attention-to-detail", "risk-assessment", "decision-making"],
    scenario: "A damaged box is labelled as cleaning cloths, but the paperwork lists cleaning liquid. The warehouse rule says to set aside damaged or mismatched goods and tell the shift lead. Do not open unknown packages.",
    problem: "Treat the mismatch as something to check, not something to guess away.",
    steps: [
      ["What is the main warning sign?", "The label and paperwork describe different contents", "A mismatch means the package cannot be handled with confidence.", ["The box is brown", "The shift is busy", "The label uses small text"]],
      ["What should you do?", "Set it aside safely and tell the shift lead", "This follows the stated rule and prevents the box moving further by mistake.", ["Open it and smell the contents", "Change the paperwork yourself", "Send it out and let the customer decide"]],
      ["Why not assume it contains cloths?", "The damaged box and conflicting record leave the contents uncertain", "One label is not enough when another trusted record disagrees.", ["Cloths are never delivered", "All damaged boxes contain liquid", "Paperwork is always false"]],
    ],
    principle: "Stop mismatched items from moving, preserve the evidence and pass the check to the responsible person.",
    limit: "A mismatch may be a simple typing error. Following the check does not accuse anyone; it prevents a small error becoming a larger one.",
  },
  {
    id: "gym-flaw-8", title: "The Delivery Location Feels Unsafe", emoji: "🚚", difficulty: 1,
    areas: ["work", "safety"], frameworks: ["situational-awareness", "boundary-setting", "decision-making"],
    scenario: "You are making a late delivery. The customer messages you to enter an unlit alley behind an empty building. Company guidance says drivers may use a safe public meeting point or mark a delivery unsafe and contact support.",
    problem: "Complete the job only through a safe method.",
    steps: [
      ["What makes the request a concern?", "It moves you alone into a dark, isolated place", "Isolation and poor visibility increase risk and reduce access to help.", ["The customer sent a message", "The parcel is small", "The address has a building number"]],
      ["What is a reasonable alternative?", "Offer a lit public meeting point and contact support if needed", "This uses the company guidance and still offers a way to complete the delivery.", ["Enter the alley to avoid a complaint", "Leave the parcel in the road", "Argue with the customer about their motive"]],
      ["The customer refuses every safe option. What now?", "Mark it unsafe and follow support instructions", "You do not need to prove bad intent before using the safety process.", ["Go in because they paid", "Share your home address", "Ask another customer to enter for you"]],
    ],
    principle: "Separate the delivery goal from an unsafe method. Offer a safe alternative and use support when it is refused.",
    limit: "An unusual location does not prove the customer is dangerous. A safer method protects both people without making that accusation.",
  },
  {
    id: "gym-flaw-9", title: "An Angry Refund Request", emoji: "🧾", difficulty: 1,
    areas: ["work", "money"], frameworks: ["communication", "policy-reading", "decision-making"],
    scenario: "A customer wants a cash refund for an item without a receipt. The displayed policy allows an exchange or store credit after the item is checked. A manager must approve any exception.",
    problem: "Explain the available options without inventing a rule.",
    steps: [
      ["What should you check first?", "The item and the displayed refund policy", "The condition of the item and written policy determine the normal options.", ["How loudly the customer complains", "Whether you personally like the item", "How much cash is in your wallet"]],
      ["What can you offer under the normal policy?", "An exchange or store credit after the check", "Those are the options stated in the scenario.", ["A guaranteed cash refund", "A replacement from your own money", "Nothing at all"]],
      ["The customer demands an exception. What next?", "Ask the manager to decide", "The policy clearly gives exception decisions to the manager.", ["Change the policy yourself", "Promise the exception before asking", "Hide the item"]],
    ],
    principle: "Use the written rule, explain the available choices and pass exceptions to the person authorised to decide.",
    limit: "Policies should not be used to dismiss people. Listen and explain clearly, while staying within the authority you actually have.",
  },
  {
    id: "gym-flaw-10", title: "A Customer Reports a Food Allergy", emoji: "🍽️", difficulty: 1,
    areas: ["work", "health", "safety"], frameworks: ["risk-assessment", "communication", "instruction-following"],
    scenario: "A restaurant customer says they have a severe nut allergy. The kitchen guide says staff must tell the duty manager and chef, check the written ingredient information and never promise that a dish is safe without confirmation.",
    problem: "Use the allergy process instead of relying on memory.",
    steps: [
      ["What should you do with the allergy information?", "Tell the duty manager and chef clearly", "The stated guide requires the people responsible for service and preparation to know.", ["Keep it to yourself", "Mention it only after the meal", "Ask another customer to decide"]],
      ["You remember that the dish has no nuts. Is memory enough?", "No, check the written information and get confirmation", "Ingredients and preparation can change, so the guide requires a current check.", ["Yes, memory is always reliable", "Yes, if the restaurant is quiet", "Only the menu price matters"]],
      ["The kitchen cannot confirm it is safe. What should you say?", "Explain that it cannot be confirmed and help find a confirmed option", "Honest uncertainty is safer than a promise the kitchen cannot support.", ["Promise it is probably fine", "Remove visible nuts and serve it", "Tell the customer allergies are their problem"]],
    ],
    principle: "Treat allergy information as safety-critical: communicate it, check current records and never turn uncertainty into a promise.",
    limit: "This challenge uses the restaurant rule shown here. Real workplaces may have additional steps that staff must follow.",
  },
  {
    id: "gym-flaw-11", title: "A Person in Your Care Seems Confused", emoji: "🫶", difficulty: 1,
    areas: ["work", "health"], frameworks: ["situational-awareness", "communication", "escalation"],
    scenario: "You support an older person who is normally alert. Today they suddenly seem confused and unsteady. Your care plan says sudden changes must be reported at once to the nurse in charge, and the person should not be left alone.",
    problem: "Act on the change without trying to diagnose it yourself.",
    steps: [
      ["What is the key fact?", "The confusion and unsteadiness are sudden changes", "A clear change from the person's normal state is the important warning.", ["The person is older", "The room is warm", "It is a weekday"]],
      ["What does the care plan tell you to do?", "Stay with them and report at once to the nurse in charge", "Both actions are stated directly in the plan.", ["Wait until tomorrow", "Ask them to walk alone", "Give medicine without instruction"]],
      ["Why should you avoid guessing the cause?", "Different causes need different trained assessment", "Reporting observed facts gets the person the right help without an unsupported diagnosis.", ["Confusion has only one cause", "Care workers may never speak", "The cause does not matter to anyone"]],
    ],
    principle: "Notice sudden change, keep the person safe and report clear observations to the responsible professional.",
    limit: "Not every moment of confusion is an emergency. The care plan makes a sudden change the reason to report promptly.",
  },
  {
    id: "gym-flaw-12", title: "The Ladder Is Missing a Foot", emoji: "🪜", difficulty: 1,
    areas: ["work", "safety"], frameworks: ["risk-assessment", "instruction-following", "decision-making"],
    scenario: "You need to reach a ceiling cable. One rubber foot is missing from the ladder, so it rocks on the floor. The site rule says damaged access equipment must be labelled, removed from use and reported.",
    problem: "Choose the safe action even though the task is short.",
    steps: [
      ["What is the relevant problem?", "The ladder rocks because a foot is missing", "The equipment is unstable and therefore damaged.", ["The cable is on the ceiling", "The job may be quick", "A coworker is nearby"]],
      ["What should you do with the ladder?", "Label it, remove it from use and report it", "That is the full site rule given in the scenario.", ["Use it while someone holds one side", "Put folded paper under it", "Leave it for the next worker"]],
      ["Why does a short job not change the answer?", "A fall can happen before the job is finished", "Short exposure can still lead to serious harm when equipment is unstable.", ["Short jobs are always harder", "Time never matters in any decision", "The ladder will repair itself"]],
    ],
    principle: "Do not trade equipment safety for speed. Remove damaged equipment so nobody else mistakes it for safe equipment.",
    limit: "This does not mean every mark or scratch makes equipment unusable. Follow the stated inspection rule and report uncertainty.",
  },
  {
    id: "gym-flaw-13", title: "Two Cleaning Products", emoji: "🧴", difficulty: 1,
    areas: ["work", "home", "health", "safety"], frameworks: ["instruction-reading", "risk-assessment", "decision-making"],
    scenario: "You are cleaning a bathroom. One bottle says: 'Do not mix with other products.' A coworker suggests adding another cleaner to make it work faster.",
    problem: "Use the warning on the product rather than an informal shortcut.",
    steps: [
      ["Which information should guide the decision?", "The warning printed on the bottle", "It directly covers the suggested action and comes from the product instructions.", ["The colour of the bottle", "How quickly the coworker speaks", "The size of the bathroom"]],
      ["What should you do?", "Use the product as directed and do not mix it", "This follows the clear safety warning.", ["Mix a small amount to test it", "Smell both products closely", "Use every cleaner available"]],
      ["The product is not working well. What is a safe next step?", "Stop and check the approved method or ask the supervisor", "A safer method can be found without breaking the warning.", ["Add more unknown chemicals", "Heat the mixture", "Remove the warning label"]],
    ],
    principle: "A clear product warning beats a shortcut. Stop and find an approved method when the instructed method is not working.",
    limit: "Different products have different instructions. Read the label each time rather than assuming all cleaners behave the same way.",
  },
  {
    id: "gym-flaw-14", title: "A Child Is Lost in the Shopping Centre", emoji: "🛡️", difficulty: 1,
    areas: ["work", "relationships", "safety"], frameworks: ["safeguarding", "communication", "instruction-following"],
    scenario: "You work in shopping-centre security. A crying child says they cannot find their parent. The procedure says to stay in a public camera-covered area, alert the control room, use two staff members and never announce the child's name.",
    problem: "Help the child while following the safeguarding procedure.",
    steps: [
      ["Where should you stay with the child?", "In the public camera-covered area", "The stated procedure keeps the interaction visible and supported.", ["Inside a locked office alone", "Outside the building", "In your personal car"]],
      ["Who should you contact?", "The control room and a second staff member", "Both are required by the procedure in the scenario.", ["Only your personal social media", "No one until closing time", "A random shopper"]],
      ["What should an announcement avoid?", "The child's name", "The procedure specifically protects that identifying detail.", ["A request for the parent to contact staff", "The meeting location for the parent", "The centre's name"]],
    ],
    principle: "Safeguarding means helping in a visible, recorded and supported way while limiting unnecessary personal information.",
    limit: "Real safeguarding procedures vary. Staff must follow their own workplace process and involve emergency services when required.",
  },
  {
    id: "gym-flaw-15", title: "Two Managers, Two Deadlines", emoji: "🗓️", difficulty: 1,
    areas: ["work"], frameworks: ["prioritisation", "communication", "decision-making"],
    scenario: "One manager asks for a stock count by 2 pm. Another asks for a customer report by the same time. Each job takes three hours, and you have four hours available. Neither manager knows about the other request.",
    problem: "Make the conflict visible before quietly missing a deadline.",
    steps: [
      ["What is the real problem?", "Both jobs cannot be completed by 2 pm with the time available", "The work needs six hours, but only four hours are available.", ["Both managers dislike you", "The jobs are impossible to complete ever", "You must choose the shortest job"]],
      ["What should you do first?", "Tell both managers about the conflict and ask which outcome matters most", "The people setting priorities need the same facts before choosing.", ["Say yes to both and hide the delay", "Pick one without telling anyone", "Work unsafely fast"]],
      ["What should your message include?", "The two requests, their effort, the shared deadline and realistic options", "Specific facts make it easier to change scope, timing or ownership.", ["A complaint about both managers", "A promise that everything will be done", "Only the task you prefer"]],
    ],
    principle: "When priorities conflict, show the full workload early and ask the responsible people to make the trade-off visible.",
    limit: "You may sometimes need to make an urgent choice yourself. Even then, explain the reason and impact as soon as you can.",
  },
  {
    id: "gym-flaw-16", title: "An Abusive Caller", emoji: "🎧", difficulty: 1,
    areas: ["work", "relationships"], frameworks: ["boundary-setting", "communication", "emotional-regulation"],
    scenario: "You work in a call centre. A caller starts insulting you. The call rule says: give one calm warning, offer help with the account problem and end or transfer the call if the abuse continues.",
    problem: "Keep the boundary clear while leaving a route back to the real problem.",
    steps: [
      ["What should the warning do?", "Name the behaviour, set the boundary and offer help with the account", "It separates the caller's problem from unacceptable treatment of staff.", ["Insult the caller back", "Threaten something outside the rule", "Pretend the abuse did not happen"]],
      ["The caller stops insulting you. What next?", "Return to the account problem", "The boundary worked, so the useful conversation can continue.", ["Demand a personal apology before any help", "End the call without explanation", "Discuss the caller with other customers"]],
      ["The abuse continues. What now?", "End or transfer the call under the rule", "The scenario gives this as the next step after the warning fails.", ["Stay on the call for any length of time", "Give out private staff details", "Make a promise you cannot keep"]],
    ],
    principle: "A good boundary is calm, specific and followed by the action you said you would take.",
    limit: "Ending abuse does not solve the account problem. Record or transfer it properly so a valid issue can still be handled safely.",
  },
  {
    id: "gym-flaw-17", title: "A Passenger Becomes Unwell", emoji: "🚌", difficulty: 1,
    areas: ["work", "health", "safety"], frameworks: ["situational-awareness", "prioritisation", "instruction-following"],
    scenario: "You drive a bus. A passenger collapses in the aisle. The company card says: stop in a safe place, secure the vehicle, call emergency help, give the location and follow the call handler's instructions.",
    problem: "Protect the whole bus while getting trained help quickly.",
    steps: [
      ["What should you do with the bus first?", "Stop safely and secure it", "A moving bus adds danger to the unwell passenger and everyone else.", ["Keep driving to stay on time", "Ask passengers to hold the steering wheel", "Reverse into traffic"]],
      ["What information should the emergency call include?", "What happened and the bus's location", "The call handler needs the situation and location to send the right help.", ["Your opinion of the passenger", "The full route timetable", "A guess about the final diagnosis"]],
      ["Who should guide any first-aid action?", "The emergency call handler and your training", "The stated rule connects action to trained guidance rather than guesswork.", ["A social media comment", "A passenger who wants to leave", "An advert on the bus"]],
    ],
    principle: "Stop new danger, call trained help and communicate clear facts rather than guessing at a diagnosis.",
    limit: "Procedures and training differ. Drivers should follow their company process and local emergency guidance.",
  },
  {
    id: "gym-flaw-18", title: "Someone Asks for a Hotel Guest's Room", emoji: "🏨", difficulty: 1,
    areas: ["work", "safety"], frameworks: ["privacy", "verification", "communication"],
    scenario: "At a hotel desk, a person asks for a guest's room number and says they are a close friend. Hotel policy says never reveal whether someone is staying or give their room number. Staff may offer to take a message.",
    problem: "Protect the guest's privacy without accusing the visitor.",
    steps: [
      ["Does being a close friend prove permission?", "No, the desk cannot verify the claim from those words", "The relationship claim is not independent permission from the guest.", ["Yes, friends may enter any room", "Yes, if the visitor sounds confident", "Only if the lobby is busy"]],
      ["What should you say?", "I cannot confirm guest details, but I can take a message", "This follows the policy and offers a safe alternative.", ["They are in room 204", "They are not here today", "Wait by the lifts and watch"]],
      ["Why can you not even confirm the stay?", "That information could help someone locate or target the guest", "Privacy includes whether the person is present, not only the room number.", ["Hotels have no rooms", "Guests never receive visitors", "The computer cannot show bookings"]],
    ],
    principle: "Verify permission before sharing personal information and offer a method that leaves control with the person concerned.",
    limit: "Emergency services or authorised staff may follow a different verified process. Use the hotel's policy for those cases.",
  },
  {
    id: "gym-workout-1", title: "Pressure to Approve a Car", emoji: "🔧", difficulty: 1,
    areas: ["work", "safety"], frameworks: ["professional-judgement", "risk-assessment", "communication"],
    scenario: "You are checking a car before it is returned. A required brake check is unfinished, but a manager says the customer is waiting and asks you to approve it now. The garage rule says an unchecked safety item cannot be signed off.",
    problem: "Handle time pressure without giving a false safety approval.",
    steps: [
      ["What fact controls the decision?", "The required brake check is unfinished", "The rule directly says an unchecked safety item cannot be approved.", ["The customer is waiting", "The manager sounds certain", "The car looks clean"]],
      ["What should you do?", "Explain the missing check and do not sign until it is completed", "This keeps the record honest and follows the safety rule.", ["Sign and check it next week", "Ask the customer to sign for you", "Remove the brake check from the form"]],
      ["What useful option can you offer?", "Give a realistic completion time or ask for another trained person to check it", "This addresses the delay without pretending the work is complete.", ["Promise it is safe without checking", "Blame the customer", "Hide the car keys"]],
    ],
    principle: "Never turn schedule pressure into a false safety record. State the missing check and offer a truthful route forward.",
    limit: "Not every unfinished task is safety-critical. This scenario states that the brake check is required before approval.",
  },
  {
    id: "gym-workout-3", title: "A Customer Dislikes Their Haircut", emoji: "✂️", difficulty: 1,
    areas: ["work", "relationships"], frameworks: ["communication", "emotional-regulation", "problem-solving"],
    scenario: "A customer looks upset after a haircut and says it is shorter than requested. You cannot put the hair back, but the salon allows a senior stylist to review the result and discuss a correction or refund.",
    problem: "Respond honestly to a mistake that cannot simply be undone.",
    steps: [
      ["What should you do first?", "Listen and ask what part differs from what they expected", "Specific information is more useful than defending the result immediately.", ["Tell them they are wrong", "Avoid looking at the haircut", "Say every customer likes it"]],
      ["What should you avoid promising?", "That the hair can be restored immediately", "That outcome is impossible, so the promise would deepen the problem.", ["That a senior stylist can review it", "That you will listen", "That the salon has a process"]],
      ["What is a practical next step?", "Acknowledge the concern and involve the senior stylist to discuss available remedies", "It combines honesty, authority and realistic choices.", ["Cut more without asking", "Post the complaint online", "Make the customer pay again before speaking"]],
    ],
    principle: "When harm cannot be fully undone, listen, acknowledge it and offer the best realistic remedy through the proper process.",
    limit: "A complaint does not automatically prove poor work. First compare the agreed request with the result and listen to the customer's concern.",
  },
  {
    id: "gym-workout-4", title: "The Coffee Shop Card Machine Is Down", emoji: "💡", difficulty: 2, creativity: true,
    areas: ["work", "money"], frameworks: ["creative-problem-solving", "constraint-thinking", "communication"],
    scenario: "The card machine stops working during the morning rush. The shop may take cash, display a clear notice and direct customers to the nearby cash machine. Staff may not record card details or offer unpaid drinks.",
    problem: "Find a useful response that stays inside every stated limit.",
    prompt: "Think of one more way to make the wait or payment choice clearer without storing card details or giving products away.",
    steps: [
      ["Which idea fits all the rules?", "Put a notice at the entrance, tell the queue and accept cash while the machine is checked", "It informs people early and uses only an allowed payment method.", ["Write down card numbers for later", "Serve everyone without payment", "Hide the problem until customers reach the till"]],
      ["How could staff reduce wasted waiting?", "Have one person explain the payment choices before customers order", "Early information lets each customer decide before joining a long queue.", ["Say nothing unless asked", "Promise the machine will work in one minute", "Lock the entrance without explanation"]],
      ["How should you judge another idea?", "Check that it is legal, clear, practical and within the shop rules", "Creative ideas are useful only when they solve the problem without creating a larger one.", ["Choose the strangest idea", "Choose the idea with the most words", "Ignore the stated limits"]],
    ],
    principle: "Creativity works best inside clear limits. Generate options, then test each one for safety, honesty and practical value.",
    limit: "There may be several good answers. The scored options test the limits shown here, not whether one idea is the only creative solution.",
  },
  {
    id: "gym-workout-5", title: "Reduce Walking at the Packing Table", emoji: "🧠", difficulty: 2, creativity: true,
    areas: ["work"], frameworks: ["process-improvement", "observation", "creative-problem-solving"],
    scenario: "At a factory packing table, workers walk six steps to collect tape for every box. The tape can be moved, but emergency paths must stay clear and sharp tools must remain in their marked holder.",
    problem: "Improve the work without moving the risk somewhere else.",
    prompt: "Sketch another layout that reduces repeated movement while keeping the emergency path and tool holder clear.",
    steps: [
      ["Which change directly removes repeated walking?", "Place the tape within safe reach at each packing position", "It removes the repeated trip while respecting the stated movable item.", ["Ask workers to walk faster", "Block the emergency path with tape boxes", "Move sharp tools into open trays"]],
      ["What should be checked before keeping the new layout?", "Whether movement falls and the path and tool rules still pass", "A small trial should measure the benefit and check that safety was preserved.", ["Whether the table looks expensive", "Whether one box was packed quickly", "Whether nobody asks questions"]],
      ["Why test a small change first?", "It reveals problems before every station is changed", "A reversible trial creates evidence at low cost.", ["Testing guarantees perfection", "Workers cannot suggest improvements", "Every layout works in every factory"]],
    ],
    principle: "Observe repeated effort, change the cause and test the result without breaking safety limits.",
    limit: "The closest position is not always the safest or fastest overall. Check reach, space and how the whole task flows.",
  },
  {
    id: "gym-workout-6", title: "Explain Fractions Without a Textbook", emoji: "🍕", difficulty: 2, creativity: true,
    areas: ["work", "study"], frameworks: ["analogy", "communication", "creative-problem-solving"],
    scenario: "A student does not understand that one half and two quarters can represent the same amount. You have paper, a pen and four equal bottle tops. The student understands sharing food equally.",
    problem: "Connect the new idea to something the student already understands.",
    prompt: "Create your own simple example of two different fractions that show the same amount.",
    steps: [
      ["Which demonstration uses the student's existing knowledge?", "Draw one pizza split in halves and another equal pizza split in quarters", "Equal pizzas make it possible to compare one half with two quarters directly.", ["Repeat the fraction names more loudly", "Use two pizzas of different sizes", "Change the subject to multiplication"]],
      ["What must stay equal for the comparison to be fair?", "The size of the whole pizza", "Fractions of different-sized wholes cannot be compared by pieces alone.", ["The colour of the pen", "The number of words used", "The student's favourite topping"]],
      ["How can the bottle tops help?", "Split four equal tops into two equal groups, then show each group has two quarters of the four", "The objects make the equal parts visible and touchable.", ["Hide three tops", "Use tops of very different sizes", "Call every top one half"]],
    ],
    principle: "A useful explanation links the new idea to a familiar one while keeping the important parts of the comparison equal.",
    limit: "An analogy supports understanding but does not replace every formal rule. Check that the student can use the idea in a new example.",
  },
  {
    id: "gym-workout-8", title: "The Delivery Road Is Closed", emoji: "🗺️", difficulty: 2, creativity: true,
    areas: ["work", "safety"], frameworks: ["adaptation", "route-planning", "constraint-thinking"],
    scenario: "A road closure blocks the next three deliveries. The van may use public roads, but it cannot enter roads marked for buses only. One parcel has a promised delivery window ending in 40 minutes; the others end later.",
    problem: "Build a new route using the limits and deadlines given.",
    prompt: "Think of another safe route or customer update that would reduce the effect of the closure.",
    steps: [
      ["What should you identify first?", "Which open legal routes can reach the parcel with the nearest deadline", "The urgent window and legal-road limit shape the useful options.", ["The fastest bus-only road", "The customer's favourite colour", "The route you always use even though it is closed"]],
      ["No legal route can meet the 40-minute window. What next?", "Update the customer or dispatcher early with an honest estimate", "Early information lets others adapt and avoids a false promise.", ["Mark it delivered", "Drive through the closure", "Turn off the tracking device"]],
      ["How should two possible routes be compared?", "Safety, legality, arrival time and effect on the later deliveries", "A creative route is only useful if it fits all important limits.", ["Choose the route with the funniest street names", "Count only distance and ignore closures", "Choose randomly without checking"]],
    ],
    principle: "When a plan breaks, keep the real constraints, generate alternatives and communicate early when no option meets the original promise.",
    limit: "The shortest route is not always the quickest or safest. Use current road information and workplace guidance.",
  },
  {
    id: "gym-workout-10", title: "A Calmer Morning With Children", emoji: "🌅", difficulty: 2, creativity: true,
    areas: ["home", "relationships"], frameworks: ["process-design", "creative-problem-solving", "habit-building"],
    scenario: "School mornings often run late. Shoes go missing, breakfast choices take too long and bags are packed at the door. You cannot change the school time, and the children still need breakfast, clothes, bags and a safe trip.",
    problem: "Change the routine instead of repeating the same rushed morning.",
    prompt: "Design one small evening change and one morning choice that could make your own routine calmer.",
    steps: [
      ["Which idea moves avoidable work out of the busy period?", "Pack bags and choose clothes the evening before", "Those tasks do not need to wait until the morning.", ["Wake everyone five minutes later", "Search for shoes only when leaving", "Add more breakfast choices"]],
      ["How could breakfast decisions be simpler?", "Offer two suitable choices instead of asking an unlimited question", "A small choice keeps involvement while reducing delay.", ["Prepare nothing and debate every option", "Skip food every day", "Let each person cook a new recipe"]],
      ["How should the new routine be tested?", "Try it for several mornings and change the part that still causes delay", "A short test shows whether the idea works in real family life.", ["Judge it after one unusual morning", "Never change it again", "Measure only whether the parent is happy"]],
    ],
    principle: "Redesign repeated problems by moving tasks, reducing decisions and improving the part that still causes delay.",
    limit: "Families have different needs, ages and resources. The best routine is one that is safe, workable and respectful for that household.",
  },
  {
    id: "gym-workout-11", title: "Make the Office Form Easier", emoji: "📝", difficulty: 2, creativity: true,
    areas: ["work"], frameworks: ["plain-language", "process-improvement", "user-centred-design"],
    scenario: "New starters often leave a form incomplete. It asks for 'authorising stakeholder details' before explaining that this means the manager who approved the request. The legal questions must remain, but headings, order and help text can change.",
    problem: "Make the form clearer without removing required information.",
    prompt: "Rewrite one confusing label from a form you know using words a new person would understand.",
    steps: [
      ["Which label is clearer?", "Manager who approved this request", "It uses the meaning people need instead of an unexplained specialist phrase.", ["Authorising stakeholder details", "Approval entity data object", "Relevant person stuff"]],
      ["Where should short help text appear?", "Beside the question where the person needs it", "Help at the point of difficulty reduces searching and guessing.", ["Only in a separate fifty-page guide", "After the form is submitted", "Hidden behind an unrelated heading"]],
      ["How can you check the redesign?", "Ask a few new starters to complete it and note where they pause", "Watching real use reveals confusion that the writer may no longer notice.", ["Ask only the original writer", "Count the number of colours", "Assume shorter always means clearer"]],
    ],
    principle: "Use the reader's words, place help where it is needed and test the result with the people who actually use it.",
    limit: "Plain language must keep the legal meaning. Ask the responsible expert to check accuracy after the wording is simplified.",
  },
  {
    id: "gym-chain-3", title: "Create Storage Without Buying Furniture", emoji: "🏠", difficulty: 2, creativity: true,
    areas: ["home", "money"], frameworks: ["constraint-thinking", "reuse", "creative-problem-solving"],
    scenario: "A small bedroom has clothes on the floor. You have strong empty boxes, labels and space under the bed. You cannot spend money or block the door, heater or walkway.",
    problem: "Use what is available while keeping the room safe and usable.",
    prompt: "Find another safe use for an item you already own instead of buying new storage.",
    steps: [
      ["Which idea fits every limit?", "Sort the clothes into labelled boxes that slide under the bed", "It uses available items, costs nothing and keeps the walkway clear.", ["Stack boxes in front of the door", "Cover the heater with clothes", "Buy a large wardrobe"]],
      ["What makes labels useful?", "They reduce the need to open every box when looking for something", "The system saves time only if people can find and return items.", ["They make boxes stronger", "They create more floor space by themselves", "They remove the need to sort"]],
      ["What should you check after a week?", "Whether items are easy to find and the safe areas remain clear", "A practical idea should work during normal use, not only on the first day.", ["Whether the boxes look new", "Whether nobody entered the room", "Whether every box is the same colour"]],
    ],
    principle: "Creativity often means seeing a new use for what is already available, then checking that the solution remains safe in daily use.",
    limit: "Cardboard is not suitable for damp areas, heavy loads or places where it creates a fire risk. Match the material to the job.",
  },
  {
    id: "gym-chain-4", title: "Plan a Good Day With £10", emoji: "🎈", difficulty: 2, creativity: true,
    areas: ["money", "relationships"], frameworks: ["budgeting", "creative-problem-solving", "trade-offs"],
    scenario: "You want to spend a day with a friend and have £10 in total. Bus travel would cost £6. A nearby park and community gallery are free, and food from home is available.",
    problem: "Create an enjoyable plan without pretending the budget is larger.",
    prompt: "Plan your own low-cost day using one free place, something from home and a small amount kept for unexpected costs.",
    steps: [
      ["Which plan stays within the budget and keeps some money spare?", "Walk to the park and gallery, bring food and keep the £10 for a drink or unexpected need", "It uses the free options and does not spend the whole budget before the day begins.", ["Spend £12 on tickets", "Take the bus and buy two £5 meals", "Borrow money without asking"]],
      ["What is the useful creative move?", "Change the activity and transport rather than giving up the whole day", "The goal is time together, so several costly methods can change.", ["Ignore every price", "Hide the budget from your friend", "Assume free places are closed"]],
      ["What should you agree with your friend?", "The budget, travel plan and what each person will bring", "Shared expectations prevent awkward spending pressure later.", ["That one person must secretly pay", "That no plan is needed", "That the most expensive option is best"]],
    ],
    principle: "Protect the real goal, change expensive methods and make the money limit visible before choosing.",
    limit: "Free activities still have limits such as opening times, access and travel safety. Check the practical details.",
  },
  {
    id: "gym-map-9", title: "Explain a Phone Contract Clearly", emoji: "📱", difficulty: 2, creativity: true,
    areas: ["work", "money"], frameworks: ["plain-language", "communication", "creative-problem-solving"],
    scenario: "You work in a phone shop. A customer does not understand '£20 per month, rising to £22 after six months, plus a £30 setup fee'. You must keep every price and condition accurate, but you can change the words and order.",
    problem: "Make a complicated offer easier to understand without hiding a cost.",
    prompt: "Rewrite one confusing price or condition you have seen so the total effect is clear to an ordinary customer.",
    steps: [
      ["Which explanation is clearest?", "You pay £30 today, then £20 a month for six months and £22 a month after that", "It puts each cost beside the time when the customer pays it.", ["The tariff has a stepped price journey", "It is only £20, apart from other charges", "Do not worry about the later price"]],
      ["Why must the later price be included?", "It changes what the customer will actually pay", "Leaving it out would make the offer sound cheaper than it is.", ["Longer explanations always sell more", "Every customer already knows it", "The setup fee replaces the monthly fee"]],
      ["How can you check the explanation?", "Ask the customer to describe the costs back in their own words", "Their explanation shows whether the important meaning was understood.", ["Ask only whether they like the phone colour", "Repeat the same phrase faster", "Remove the figures"]],
    ],
    principle: "Plain language keeps every important fact but puts it in the order and words the listener needs.",
    limit: "Simpler wording must not remove a cost, condition or risk. Accuracy and clarity have to work together.",
  },
  {
    id: "gym-map-10", title: "Improve a Shopping Bag for an Older Customer", emoji: "🛍️", difficulty: 2, creativity: true,
    areas: ["work", "home"], frameworks: ["user-centred-design", "observation", "creative-problem-solving"],
    scenario: "A supermarket customer says the thin bag handles hurt their hands and the bag tips over in the car. A new design must still fold flat, carry the same shopping and cost little to make.",
    problem: "Improve the bag for the person using it while keeping the practical limits.",
    prompt: "Choose an everyday object and suggest one change for a person who finds the current version difficult to use.",
    steps: [
      ["Which idea addresses both reported problems?", "Use wider soft handles and a flat reinforced base", "Wider handles spread pressure, while a flat base helps the bag stay upright.", ["Make the bag taller with the same thin handles", "Print larger adverts on it", "Remove the handles"]],
      ["What should be tested with customers?", "Comfort, stability, capacity and whether it still folds flat", "These checks cover the user's problems and every stated limit.", ["Only the bag colour", "Whether staff can guess the result", "Whether it looks unusual"]],
      ["Why involve people who have the problem?", "They can reveal difficulties the designer may not notice", "Designing with users gives evidence about real use rather than assumptions.", ["They must accept every first idea", "Designers are never allowed ideas", "One person represents every customer"]],
    ],
    principle: "Start with the difficulty a person actually experiences, generate changes and test them against both user needs and practical limits.",
    limit: "One design will not suit everyone. Testing with several people helps reveal different needs and new trade-offs.",
  },
];

for (const replacement of MTC_EVERYDAY_REPLACEMENTS) {
  const challenge = MTC_GYM_CHALLENGES.find((item) => item.id === replacement.id);
  if (!challenge) continue;
  const creative = Boolean(replacement.creativity);
  Object.assign(challenge, {
    format: "workout",
    title: replacement.title,
    scenario: replacement.scenario,
    difficulty: replacement.difficulty,
    emoji: replacement.emoji,
    frameworks: replacement.frameworks,
    lifeAreas: replacement.areas,
    hint: creative
      ? "Start with the limits. A useful new idea must still be safe, honest and possible."
      : "Everything you need is in the situation and the stated rule. Use those facts rather than job knowledge.",
    payload: {
      problem: replacement.problem,
      everydayReplacement: true,
      creativity: creative,
      creativePrompt: replacement.prompt || "",
      fairnessNote: creative
        ? "There may be other good ideas. Points come from choosing the option that best fits every limit shown."
        : "Use only the facts and rules shown here. You do not need experience in this job.",
      steps: replacement.steps.map(([ask, correct, because, wrong]) => ({
        ask,
        options: [correct, ...wrong],
        answer: 0,
        because,
      })),
    },
    debrief: {
      principle: replacement.principle,
      whereItMisleads: replacement.limit,
    },
  });
}
